.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandSkyControllerCalibrationStateMagnetoCalibrationStateV2Listener;
.super Ljava/lang/Object;
.source "ARCommandSkyControllerCalibrationStateMagnetoCalibrationStateV2Listener.java"


# virtual methods
.method public abstract onSkyControllerCalibrationStateMagnetoCalibrationStateV2Update(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_SKYCONTROLLER_CALIBRATIONSTATE_MAGNETOCALIBRATIONSTATEV2_STATE_ENUM;)V
.end method
