.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandSkyControllerAccessPointSettingsStateWifiSecurityChangedListener;
.super Ljava/lang/Object;
.source "ARCommandSkyControllerAccessPointSettingsStateWifiSecurityChangedListener.java"


# virtual methods
.method public abstract onSkyControllerAccessPointSettingsStateWifiSecurityChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_SKYCONTROLLER_ACCESSPOINTSETTINGSSTATE_WIFISECURITYCHANGED_SECURITY_TYPE_ENUM;Ljava/lang/String;)V
.end method
