.class public interface abstract Lcom/parrot/arsdk/arcommands/ARCommandMiniDroneVideoSettingsStateElectricFrequencyChangedListener;
.super Ljava/lang/Object;
.source "ARCommandMiniDroneVideoSettingsStateElectricFrequencyChangedListener.java"


# virtual methods
.method public abstract onMiniDroneVideoSettingsStateElectricFrequencyChangedUpdate(Lcom/parrot/arsdk/arcommands/ARCOMMANDS_MINIDRONE_VIDEOSETTINGSSTATE_ELECTRICFREQUENCYCHANGED_FREQUENCY_ENUM;)V
.end method
